version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: civicstream-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: civicstream123
      MONGO_INITDB_DATABASE: civicstream
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - civicstream-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: civicstream-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - civicstream-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # CivicStream Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: civicstream-backend
    restart: unless-stopped
    environment:
      # Database
      MONGODB_URL: mongodb://admin:civicstream123@mongodb:27017/civicstream?authSource=admin
      MONGODB_DB_NAME: civicstream
      
      # Security
      SECRET_KEY: ${SECRET_KEY:-your-secret-key-change-in-production}
      
      # Optional services
      REDIS_URL: redis://redis:6379
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app:ro  # Mount source code for development
      - upload_data:/app/uploads
    networks:
      - civicstream-network
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MongoDB Express (Database Admin UI)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: civicstream-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: civicstream123
      ME_CONFIG_MONGODB_URL: mongodb://admin:civicstream123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: civicstream123
    ports:
      - "8081:8081"
    networks:
      - civicstream-network
    depends_on:
      mongodb:
        condition: service_healthy
    profiles:
      - admin

  # Nginx reverse proxy (for production)
  nginx:
    image: nginx:alpine
    container_name: civicstream-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - civicstream-network
    depends_on:
      - backend
    profiles:
      - production

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
  upload_data:
    driver: local

networks:
  civicstream-network:
    driver: bridge